version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
  - main
configuration: Release
install:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    rem git submodule update --init --recursive
    rem set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    rem choco install ilmerge
    rem set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;%APPVEYOR_BUILD_FOLDER%\IronScheme\tools\;
    choco install dotnet-9.0-sdk --pre -y -r
    for /d %%d in (%LOCALAPPDATA%\Microsoft\VisualStudio\17.0*) do echo UsePreviews=True > %%d\sdk.txt
    for /d %%d in (%LOCALAPPDATA%\Microsoft\VisualStudio\17.0*) do type %%d\sdk.txt
    rem dotnet --info
build_script:
- cmd: |
    set ARGS=-restore -tl:off -v:m -m:1 test.csproj
    msbuild %ARGS% 
    rd /s /q obj && rd /s /q bin
    dotnet msbuild %ARGS% 
    rd /s /q obj && rd /s /q bin
    dotnet build %ARGS%
    rd /s /q obj && rd /s /q bin
    msbuild %ARGS% /p:UseNetFxIlTools=false
    rd /s /q obj && rd /s /q bin
    dotnet msbuild %ARGS% /p:UseNetFxIlTools=false
    rd /s /q obj && rd /s /q bin
    dotnet build %ARGS% /p:UseNetFxIlTools=false
