version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
  - main
configuration: Release
platform: Any CPU
install:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    git submodule update --init --recursive
    set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    choco install ilmerge
    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;%APPVEYOR_BUILD_FOLDER%\IronScheme\tools\;
    choco install dotnet-9.0-sdk --pre -y
    set
    where msbuild
    msbuild -noLogo -ver
    where dotnet
    dotnet msbuild -ver
    dotnet --info
build_script:
- cmd: |
    dotnet build -tl:off -v n
    dotnet msbuild -tl:off -v:n
    msbuild
