version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
  - main
configuration: Release
install:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    git submodule update --init --recursive
    set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    choco install ilmerge
    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;%APPVEYOR_BUILD_FOLDER%\IronScheme\tools\;
    choco install dotnet-9.0-sdk --pre -y -r
    for /d %%d in (%LOCALAPPDATA%\Microsoft\VisualStudio\17.0*) do echo UsePreviews=True > %%d\sdk.txt
    for /d %%d in (%LOCALAPPDATA%\Microsoft\VisualStudio\17.0*) do type %%d\sdk.txt
build_script:
- cmd: |
    dotnet build /tl:off -m:1 /p:UseNetFxIlTools=true
    dotnet msbuild -restore /tl:off -m:1 /p:UseNetFxIlTools=true 
    msbuild -restore -m:1 /p:UseNetFxIlTools=true
    dotnet build /tl:off -m:1 /p:UseNetFxIlTools=false 
    dotnet msbuild -restore /tl:off -m:1 /p:UseNetFxIlTools=false
    msbuild -restore -m:1 /p:UseNetFxIlTools=false
    dotnet build /tl:off -m:1
    dotnet msbuild -restore /tl:off -m:1
    msbuild -restore -m:1
